[package]
name = "teotile"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.72"
crossterm = "0.26.1"
defmt = "0.3.5"
rand = "0.8.5"
smallvec = "1.11.0"
