[package]
name = "teotile-web"
version = "0.1.0"
edition = "2021"

[dependencies]
wasm-bindgen = "0.2.92"
web-sys = { version = "0.3.69", features = ["console"] }
teotile = { path = "../engine" }

[lib]
crate-type = ["cdylib"]
